name: Bump version
on:
  push:
    branches:
      - master
      - release
      - develop
  pull_request:
    branches:
      - master
      - release
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.7.0
      - name: Bump version and push tag
        id: tag_version
        uses: HZKnight/github-tag-action@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true
          prerelease: true
